_admin_ajouter_events:
    path:     /adminajoutevent
    defaults: { _controller: EvenementBundle:Evenement:adminAjout }

_admin_modifier_events:
    path:     /adminmodifierevent
    defaults: { _controller: EvenementBundle:Evenement:adminModifier }

_admin_supprimer_events:
    path:     /adminsupprimerevent
    defaults: { _controller: EvenementBundle:Evenement:adminSupprimer }

_admin_afficher_events:
    path:     /adminafficherevents
    defaults: { _controller: EvenementBundle:Evenement:adminAfficher }